apiVersion: apps/v1
kind: Deployment
metadata:
  name: chef-service-latest
spec:
  selector: # the deployment target a set of pods with the following labels
    matchLabels:
      app: chef-service
      version: latest
  replicas: 1
  template:
    metadata:
      labels: # the labels of our pods
        app: chef-service
        version: latest
    spec:
      containers:
      - name: chef-service-container
        image: marcdestefanis/chef-service:latest # pull the image from Docker Hub
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "50m"
            memory: "512Mi"
        env:
        - name: "spring.profiles.active"
          value: default
        ports:
        - containerPort: 80 # port exposed in our Dockerfile