apiVersion: apps/v1
kind: Deployment
metadata:
  name: bakery-service-latest
spec:
  selector: # the deployment target a set of pods with the following labels
    matchLabels:
      app: bakery-service
      version: latest
  replicas: 1
  template:
    metadata:
      labels: # the labels of our pods
        app: bakery-service
        version: latest
    spec:
      containers:
      - name: bakery-service-container
        image: marcdestefanis/bakery-service:latest # pull the image from Docker Hub
        imagePullPolicy: Always
        env:
        - name: "spring.profiles.active"
          value: default
        ports:
        - containerPort: 80 # port exposed in our Dockerfile